### ISSUE TITLE
Get and display Pokemon in scene

### ISSUE THREAD

**Issue by hannahschwen** [group11projectpokemon/group-11-project-pokemon#39]
- [x] **Get API data**
Write a function to get api data for each pokemon in the array. You will need at least the image, cry, and possible a unique id, depending on how the function to delete will work. A function called fetchPokeImg has already been written for this in the pokemon.js file, but it may need to be adjusted.
- [x] **Save info in object**
Save the info as pokemon objects. Look at current function fetchPokeImg
- [x] **Display pokemon images in scene**
Use the data obtained to display the pokemon’s pic in its appropriate div. The pokemon should append to the div coordinating with the log chosen in the modal by the user. Log A goes in #slot0, Log B goes in #slot1, Log C goes in #slot2, and Log D goes in #slot3
Currently, a createCard function is being run to display the data in cards. Instead of making cards, the images only need to be appended to the appropriate div.
- [x] **Pokemon play their cry when clicked**
A function has already been written for this in the volume.js file. Make sure it still functions on the pokemon around the campfire

**Comment by swokamoto** [comment]
API data saved as an object to local storage

function made to display pokemon with dataset tags

event listeners added to play cry when clicked
